- name: Install nginx
  apt: pkg=nginx,python-passlib state=installed update_cache=true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Copy nginx configuration file (non-ssl)
  template: src=nginx-site-default dest=/etc/nginx/sites-available/{{ project_name }}
  notify: restart nginx
  when: not ssl and not custom_nginx_template | is_file

- name: Copy nginx configuration file (ssl)
  template: src=nginx-site-default-ssl dest=/etc/nginx/sites-available/{{ project_name }}
  notify: restart nginx
  when: ssl and not custom_nginx_template | is_file

- name: Copy custom nginx template
  template: src={{ custom_nginx_template }} dest=/etc/nginx/sites-available/{{ project_name }}
  when: custom_nginx_template | is_file

- name: Symlink nginx configuration file
  file: src=/etc/nginx/sites-available/{{ project_name }} dest=/etc/nginx/sites-enabled/{{ project_name }} state=link
  notify: restart nginx

- name: Create basic auth user file
  htpasswd: path=/etc/nginx/{{ project_name }}.htpasswd name={{ basic_auth_user }} password={{ basic_auth_password }} owner=root group=www-data mode=0640
  when: basic_auth

- name: Create Firewall rule for port 80
  ufw: rule=allow port={{ webserver_port }} proto=tcp
  when: enable_fw

- name: Create Firewall rule for port 443
  ufw: rule=allow port=443 proto=tcp
  when: ssl and enable_fw

# SSL
- name: Install Let's Encrypt
  apt: pkg=letsencrypt update_cache=true
  when: letsencrypt and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Create Let's Encrypt directory
  file: path=/tmp/letsencrypt state=directory
  when: letsencrypt

- name: Generate dhparam file
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048 creates=/etc/ssl/certs/dhparam.pem
  notify: restart nginx
  when: ssl

- name: Generate initial certificate
  command: bash -c "systemctl stop nginx; letsencrypt certonly --standalone -d {{ domain }} {% if use_www %}-d www.{{ domain }}{% endif %} -m {{ letsencrypt_email }} --agree-tos; systemctl start nginx" creates=/etc/letsencrypt
  notify: restart nginx
  when: letsencrypt

- name: Create scripts directory
  file: path={{ root_dir }}/scripts state=directory
  when: letsencrypt

- name: Create renew cronjob script
  template: src=update-certs.sh dest={{ root_dir }}/scripts/update-certs.sh mode=a+x
  when: letsencrypt

- name: Install renew cronjob
  cron: name="update letsencrypt certificates" minute="0" hour="0" weekday="1" job="/srv/{{ project_name }}/scripts/update-certs.sh"
  when: letsencrypt

- name: Reload nginx
  service: name=nginx state=reloaded
  tags: deploy
